# Generated by Django 2.2.12 on 2020-05-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200518_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='teste', max_length=200),
            preserve_default=False,
        ),
    ]
