# Generated by Django 2.2.12 on 2020-05-20 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_discount_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total')),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Ordem Serviço')),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('paid', 'paid'), ('disapproved', 'disapproved')], default='waiting', max_length=32, verbose_name='Status')),
                ('payment_method', models.CharField(max_length=200, verbose_name='Método de pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.Template')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
