# Generated by Django 2.2.12 on 2020-06-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoiceorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='template',
        ),
        migrations.AddField(
            model_name='discount',
            name='template',
            field=models.ManyToManyField(blank=True, null=True, related_name='discount', to='core.Template'),
        ),
    ]
