# Generated by Django 2.2.12 on 2020-06-04 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200604_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='template',
        ),
        migrations.AddField(
            model_name='discount',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='core.Template'),
        ),
    ]
