# Generated by Django 2.2.12 on 2020-06-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200605_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateimage',
            name='originals',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='thumbnails',
            field=models.CharField(max_length=1024),
        ),
    ]
