# Generated by Django 2.2.12 on 2020-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200619_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
