export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE'

export const USER_AUTH = 'USER_AUTH'

export const TOAST_OPEN = 'TOAST_OPEN'

export const TOAST_CLOSE = 'TOAST_CLOSE'

export const TEMPLATE_DETAIL = 'TEMPLATE_DETAIL'