version: '2'
services:
  indow_nginx:
    container_name: indow_container
    image: nginx
    network_mode: "host"
    volumes:
      - ../nginx/default_local:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

